// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	checkout "viniti.us/hashout/models/checkout"
)

// ProductRepository is an autogenerated mock type for the Repository type
type ProductRepository struct {
	mock.Mock
}

// FindAll provides a mock function with given fields: items
func (_m *ProductRepository) FindAll(items []checkout.Item) ([]checkout.Item, error) {
	ret := _m.Called(items)

	var r0 []checkout.Item
	if rf, ok := ret.Get(0).(func([]checkout.Item) []checkout.Item); ok {
		r0 = rf(items)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]checkout.Item)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func([]checkout.Item) error); ok {
		r1 = rf(items)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindLastByIsGift provides a mock function with given fields: isGift
func (_m *ProductRepository) FindLastByIsGift(isGift bool) (checkout.Product, error) {
	ret := _m.Called(isGift)

	var r0 checkout.Product
	if rf, ok := ret.Get(0).(func(bool) checkout.Product); ok {
		r0 = rf(isGift)
	} else {
		r0 = ret.Get(0).(checkout.Product)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(bool) error); ok {
		r1 = rf(isGift)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
