// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// HashoutApp is an autogenerated mock type for the Config type
type HashoutApp struct {
	mock.Mock
}

// GetAllowedGiftsPerCart provides a mock function with given fields:
func (_m *HashoutApp) GetAllowedGiftsPerCart() int {
	ret := _m.Called()

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// GetBlackFridayDay provides a mock function with given fields:
func (_m *HashoutApp) GetBlackFridayDay() int {
	ret := _m.Called()

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// GetBlackFridayMonth provides a mock function with given fields:
func (_m *HashoutApp) GetBlackFridayMonth() time.Month {
	ret := _m.Called()

	var r0 time.Month
	if rf, ok := ret.Get(0).(func() time.Month); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(time.Month)
	}

	return r0
}

// IsBlackFridayGiftActive provides a mock function with given fields:
func (_m *HashoutApp) IsBlackFridayGiftActive() bool {
	ret := _m.Called()

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}
