// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package app

import (
	"viniti.us/hashout/clients"
	"viniti.us/hashout/config/app"
	"viniti.us/hashout/config/cb"
	"viniti.us/hashout/config/db"
	"viniti.us/hashout/config/grpc"
	"viniti.us/hashout/handlers"
	"viniti.us/hashout/handlers/server"
	"viniti.us/hashout/storage"
	"viniti.us/hashout/usecase/checkout"
	"viniti.us/hashout/usecase/discounts"
)

// Injectors from wire.go:

func SetupApplication() *server.Api {
	engine := server.NewRouter()
	productDataset := db.NewConnection()
	productRepository := storage.NewProductRepository(productDataset)
	context := grpc.NewContext()
	discountClient := grpc.NewDiscountGRPCClient()
	discountCB := cb.NewDiscountCB()
	clientsDiscountClient := clients.NewDiscountClient(context, discountClient, discountCB)
	useCase := discounts.NewUseCase(clientsDiscountClient)
	hashoutApp := app.NewAppConfig()
	checkoutUseCase := checkout.NewUseCase(productRepository, useCase, hashoutApp)
	checkoutHandler := handlers.NewCheckoutHandler(checkoutUseCase)
	httpServer := server.NewHttpServer(engine, checkoutHandler)
	api := &server.Api{
		Server: httpServer,
	}
	return api
}
