// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package app

import (
	"viniti.us/hashout/config/db"
	"viniti.us/hashout/handlers"
	"viniti.us/hashout/handlers/server"
	"viniti.us/hashout/storage"
	"viniti.us/hashout/usecase/checkout"
)

// Injectors from wire.go:

func SetupApplication() *server.Api {
	engine := server.NewRouter()
	productsDataset := db.NewConnection()
	productRepository := storage.NewProductRepository(productsDataset)
	useCase := checkout.NewUseCase(productRepository)
	checkoutHandler := handlers.NewCheckoutHandler(useCase)
	httpServer := server.NewHttpServer(engine, checkoutHandler)
	api := &server.Api{
		Server: httpServer,
	}
	return api
}
