// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	context "context"

	discount "viniti.us/hashout/pb"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"
)

// DiscountClient is an autogenerated mock type for the DiscountClient type
type DiscountClient struct {
	mock.Mock
}

// GetDiscount provides a mock function with given fields: ctx, in, opts
func (_m *DiscountClient) GetDiscount(ctx context.Context, in *discount.GetDiscountRequest, opts ...grpc.CallOption) (*discount.GetDiscountResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *discount.GetDiscountResponse
	if rf, ok := ret.Get(0).(func(context.Context, *discount.GetDiscountRequest, ...grpc.CallOption) *discount.GetDiscountResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*discount.GetDiscountResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *discount.GetDiscountRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
