// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	checkout "viniti.us/hashout/models/checkout"

	mock "github.com/stretchr/testify/mock"
)

// ProductDataset is an autogenerated mock type for the Database type
type ProductDataset struct {
	mock.Mock
}

// FindLastProductByIsGift provides a mock function with given fields: isGift
func (_m *ProductDataset) FindLastProductByIsGift(isGift bool) (checkout.Product, bool) {
	ret := _m.Called(isGift)

	var r0 checkout.Product
	if rf, ok := ret.Get(0).(func(bool) checkout.Product); ok {
		r0 = rf(isGift)
	} else {
		r0 = ret.Get(0).(checkout.Product)
	}

	var r1 bool
	if rf, ok := ret.Get(1).(func(bool) bool); ok {
		r1 = rf(isGift)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// FindProductByID provides a mock function with given fields: id
func (_m *ProductDataset) FindProductByID(id int32) (checkout.Product, bool) {
	ret := _m.Called(id)

	var r0 checkout.Product
	if rf, ok := ret.Get(0).(func(int32) checkout.Product); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(checkout.Product)
	}

	var r1 bool
	if rf, ok := ret.Get(1).(func(int32) bool); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}
